export const CHNAGE_INPUT_VALUE = 'change_input_value'
export const INPUT_SUBMIT = 'input_submit'
export const LIST_DELETE = 'list_delete'
export const INIT_LIST = 'init_list'
export const SAGA_INIT_LIST = 'saga_init_list'